### ISSUE TITLE
issue about firebase and package_info_plus 5.0.1 requires web ^0.5.1

### ISSUE THREAD

**Issue by spiderman16888** [tazatechnology/flutter_app_info#2]
trouble with:
  firebase_core: ^2.27.1
  firebase_analytics: ^10.8.10
  firebase_auth: ^4.17.9
  flutter_signin_button: ^2.0.0
  firebase_database: ^10.4.10

error: 
Because firebase_auth >=4.17.9 depends on firebase_auth_web ^5.10.0 which depends on web ^0.5.1, firebase_auth >=4.17.9 requires web ^0.5.1.
And because package_info_plus 5.0.1 depends on web >=0.3.0 <0.5.0 and no versions of package_info_plus match >5.0.1 <6.0.0, firebase_auth >=4.17.9 is incompatible with package_info_plus ^5.0.1.
And because flutter_app_info 2.0.0 depends on package_info_plus ^5.0.1 and no versions of flutter_app_info match >2.0.0 <3.0.0, firebase_auth >=4.17.9 is incompatible with flutter_app_info ^2.0.0.
So, because com.wfco.brc depends on both flutter_app_info ^2.0.0 and firebase_auth ^4.17.9, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on flutter_app_info: flutter pub add flutter_app_info:^1.1.2

**Comment by walsha2** [comment]
Package versions updated as of latest release:

https://pub.dev/packages/flutter_app_info/versions/3.0.0
